defaults:
  - lewm
  - override data: lunarlander_heuristic_random
  - _self_

output_model_name: lewm_lunarlander_heuristic_random
subdir: ""
run_dir: /media/hdd1/physics-priors-latent-space/lunar-lander-networks/lewm-runs/heuristic-random

wm:
  action_dim: 2

wandb:
  enabled: False
